######## Execution Environment #########
execution_env=local
#execution_env=remote
#execution_env=lambdatest

appURL=https://tutorialsninja.com/demo
email=gfhgxfdh@gmail.com
password=Test@123
searchProductName=iphone